# prettier.arrowParens
# prettier.bracketSpacing
# prettier.endOfLine
# prettier.htmlWhitespaceSensitivity
# prettier.insertPragma
# prettier.singleAttributePerLine
# prettier.bracketSameLine
# prettier.jsxBracketSameLine
# prettier.jsxSingleQuote
# prettier.printWidth
# prettier.proseWrap
# prettier.quoteProps
# prettier.requirePragma
# prettier.semi
# prettier.singleQuote
# prettier.tabWidth
# prettier.trailingComma
# prettier.useTabs
# prettier.vueIndentScriptAndStyle
# prettier.embeddedLanguageFormatting

trailingComma: "es5"
tabWidth: 2
semi: false
singleQuote: true
jsxSingleQuote: true
bracketSameLine: true
bracketSpacing: true
arrowParens: "avoid"
printWidth: 90
endOfLine: "lf"